name: OWASP Dependency-Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dependency-check:
    name: Run OWASP Dependency-Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download OWASP Dependency-Check
        run: |
          curl -sL "https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip" --output dependency-check.zip
          unzip dependency-check.zip

      - name: Run Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --project "Simple Flask App" \
            --scan . \
            --format JSON \
            --out dependency-check-report.json

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.json
